"""create marketplaces table

Revision ID: 447f15f895e6
Revises: 
Create Date: 2026-08-04 18:50:18.105155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447f15f895e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable marketplace name'),
    sa.Column('code', sa.String(length=30), nullable=False, comment='Unique marketplace code (e.g. daraz, amazon, ebay)'),
    sa.Column('base_url', sa.String(length=255), nullable=False, comment='Marketplace base URL'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indicates whether the marketplace is active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
