"""create marketplace sellers table

Revision ID: 5b4aaf67d022
Revises: e7bbc303f8a7
Create Date: 2026-08-11 17:15:31.441659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b4aaf67d022'
down_revision: Union[str, Sequence[str], None] = 'e7bbc303f8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_sellers',
    sa.Column('seller_id', sa.UUID(), nullable=False, comment='Canonical seller represented by this marketplace identity'),
    sa.Column('marketplace_id', sa.UUID(), nullable=False, comment='Marketplace where this seller identity exists'),
    sa.Column('marketplace_region_id', sa.UUID(), nullable=False, comment='Regional storefront where this seller identity exists'),
    sa.Column('marketplace_seller_id', sa.String(length=150), nullable=False, comment='External seller identifier assigned by the marketplace'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Seller name displayed by the marketplace'),
    sa.Column('profile_url', sa.String(length=1000), nullable=True, comment='Marketplace seller profile URL'),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False, comment='Marketplace seller lifecycle status'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("true"), nullable=False, comment='Indicates whether the marketplace seller identity is active'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last successful marketplace synchronization'),
    sa.Column('sync_status', sa.String(length=30), server_default='pending', nullable=False, comment='Marketplace seller synchronization status'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Latest marketplace seller synchronization error'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Number of synchronization retries'),
    sa.Column('raw_marketplace_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw marketplace seller response retained for traceability'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['marketplace_region_id'], ['marketplace_regions.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace_id', 'marketplace_region_id', 'marketplace_seller_id', name='uq_marketplace_sellers_marketplace_region_seller')
    )
    op.add_column('marketplace_products', sa.Column('marketplace_seller_id', sa.UUID(), nullable=False, comment='Marketplace seller responsible for this listing'))
    op.create_foreign_key('fk_marketplace_products_marketplace_seller_id', 'marketplace_products', 'marketplace_sellers', ['marketplace_seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_marketplace_products_marketplace_seller_id', 'marketplace_products', type_='foreignkey')
    op.drop_column('marketplace_products', 'marketplace_seller_id')
    op.drop_table('marketplace_sellers')
    # ### end Alembic commands ###
