"""create brands table

Revision ID: 7c48376e8838
Revises: 447f15f895e6
Create Date: 2026-08-04 19:20:23.610152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c48376e8838'
down_revision: Union[str, Sequence[str], None] = '447f15f895e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=150), nullable=False, comment='Official brand name'),
    sa.Column('slug', sa.String(length=150), nullable=False, comment='URL-friendly unique brand identifier'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='Brand logo URL'),
    sa.Column('website', sa.String(length=255), nullable=True, comment='Official brand website'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("true"), nullable=False, comment='Indicates whether the brand is active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brands')
    # ### end Alembic commands ###
