"""create marketplace products table

Revision ID: 85a4d24d0dda
Revises: aea7d4f42701
Create Date: 2026-08-08 14:26:59.227875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85a4d24d0dda'
down_revision: Union[str, Sequence[str], None] = 'aea7d4f42701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_products',
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Canonical product represented by this marketplace listing'),
    sa.Column('marketplace_id', sa.UUID(), nullable=False, comment='Marketplace containing this listing'),
    sa.Column('marketplace_region_id', sa.UUID(), nullable=False, comment='Regional storefront containing this listing'),
    sa.Column('marketplace_product_id', sa.String(length=150), nullable=False, comment='External product/listing identifier assigned by the marketplace'),
    sa.Column('url', sa.String(length=1000), nullable=False, comment='Current marketplace product URL'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Marketplace-specific product title'),
    sa.Column('sku', sa.String(length=150), nullable=True, comment='Marketplace-specific SKU'),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False, comment='Marketplace listing lifecycle status'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indicates whether the marketplace listing is active'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last successful marketplace synchronization'),
    sa.Column('sync_status', sa.String(length=30), server_default='pending', nullable=False, comment='Marketplace synchronization status'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Latest marketplace synchronization error'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Number of synchronization retries'),
    sa.Column('raw_marketplace_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw marketplace response retained for traceability'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['marketplace_region_id'], ['marketplace_regions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace_id', 'marketplace_region_id', 'marketplace_product_id', name='uq_marketplace_products_marketplace_region_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplace_products')
    # ### end Alembic commands ###
