"""create price history table

Revision ID: ac29d9cd75d7
Revises: cc390763110a
Create Date: 2026-08-16 12:03:50.039440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac29d9cd75d7'
down_revision: Union[str, Sequence[str], None] = 'cc390763110a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('marketplace_product_id', sa.UUID(), nullable=False, comment='Marketplace product whose price was observed'),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Historical monetary price amount'),
    sa.Column('currency_code', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('price_type', sa.String(length=30), server_default='regular', nullable=False, comment='Price type such as regular, sale, or promotion'),
    sa.Column('availability_status', sa.String(length=30), server_default='unknown', nullable=False, comment='Product availability status at the time of observation'),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the marketplace price was observed'),
    sa.Column('raw_marketplace_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw marketplace response retained for traceability'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_product_id'], ['marketplace_products.id'], name='fk_price_history_marketplace_product_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    # ### end Alembic commands ###
