"""create current prices table

Revision ID: cc390763110a
Revises: 5b4aaf67d022
Create Date: 2026-08-11 17:52:03.344836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc390763110a'
down_revision: Union[str, Sequence[str], None] = '5b4aaf67d022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_prices',
    sa.Column('marketplace_product_id', sa.UUID(), nullable=False, comment='Marketplace product whose current price is represented'),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Current monetary price amount'),
    sa.Column('currency_code', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('price_type', sa.String(length=30), server_default='regular', nullable=False, comment='Price type such as regular, sale, or promotion'),
    sa.Column('availability_status', sa.String(length=30), server_default='unknown', nullable=False, comment='Current product availability status'),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the current price was observed'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_product_id'], ['marketplace_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace_product_id', name='uq_current_prices_marketplace_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_prices')
    # ### end Alembic commands ###
