"""add reference amounts for discount analysis

Revision ID: e6192a68f2f7
Revises: ac29d9cd75d7
Create Date: 2026-08-16 12:48:28.893765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6192a68f2f7'
down_revision: Union[str, Sequence[str], None] = 'ac29d9cd75d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_prices', sa.Column('reference_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='Marketplace-provided reference or original price used for discount display'))
    op.add_column('price_history', sa.Column('reference_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='Marketplace-provided reference or original price at the time of observation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'reference_amount')
    op.drop_column('current_prices', 'reference_amount')
    # ### end Alembic commands ###
